siteName = "HRocket"
theme = "HR_Publisher"
disqusShortname = ""
BuilPath = "/home/noushervan/hrocket/docs"
publishDir = "/hrocket-test"
logoLink = "/"
metaKeywords = "HTML, CSS, XML, XHTML, JavaScript"
googleAnalyticsTrackingId = "UA-232232-34"
siteUrl = "http://example.com"
robotsAllow = "False"

[[mainMenu]]
  name = "Home"
  url = "/hrocket-test"
[[mainMenu]]
  name = "About"
  url = "/hrocket-test/content/pages/about"
[[mainMenu]]
  name = "Blogs"
  url = "/hrocket-test/content/pages/blogs"


[params]
    description = ""
    [params.logo]
      url = "logo.png"
      width = 50
      height = 50
      alt = "Logo"
    [params.favIcon]
      url = "favicon.ico"

